 <h1 style="text-align: center; color: RED">İÇERİK TEMELLİ FİLTRELEME</h1>

İçerik temelli filtreleme, öneri sistemlerinde kullanıcıların geçmişteki tercihlerine göre benzer içerikleri önermek için kullanılan bir yöntemdir. Bu yöntem, kullanıcılara daha önce ilgisini çeken öğeleri, özelliklerine dayanarak önerir. Yani, her öğe (örneğin, bir film, bir kitap veya bir ürün) belirli özelliklere (etiketler, kategoriler, metin özellikleri, vb.) sahiptir ve içerik temelli filtreleme bu özellikler üzerinden benzerlik kurarak önerilerde bulunur.

Ürün içeriklerinin(meta bilgileri) benzerlikleri üzerinden tavsiyeler geliştirilir.Örneğin kitap bir üründür, kitap içerikleri ise benzerlikleridir.Ürün içeriğine göre tavsiye yapabilmek için öyle bir şey yaplıyız ki içerikleri kullanarak matematiksel bir form elde ederek metni ölçülebilir bir form haline getirebilmeliyiz.Böylece diğer ürünler ile arasında kıyaslama yapabilme şansı elde ederiz.Bunu yapabilmenin adımları:

**1-)Metinleri vektörleştirme(Metinleri matematiksel olarak temsil et)**

   Metni matematiksel olarak ölçülebilir hale getirmeliyiz.Bunu şu yöntemler ile yapabiliriz:
   
   •	Count Vector(Word count) 
   
   •	TF-ID

![Test](datasets/11.png) Metinlerde bulunan her bir eşsiz kelime sayısı matematiksel olarak ifade edildi. Örneğin Word2 kelimesi movie1 de 2 kere, Movie2 de 1 kere geçmiştir.Bu filmlerin benzerliklerini  öklid uzaklıklarını hesaplayarak bulabiliriz.

**2)Benzerlikleri Hesapla**

Aşağıda belirttiğimiz iki yöntemle benzerlikleri hesaplayabiliriz. Bu benzerlikler üzerinden kullanıcıya tavsiyelerde bulunabiliriz.

![Test](datasets/12.png)

•	Euclidean Distance:

o	İki öğe arasındaki mesafeyi hesaplar. Mesafe ne kadar küçükse, öğeler o kadar benzer kabul edilir.


![Test](datasets/13.png)

•	Cosine Similarity:

o	İki öğe arasındaki açıya bakarak benzerlik ölçümü yapar. Öğelerin özellik vektörlerinin yönü ne kadar yakınsa, o kadar benzer kabul edilir.

o	Cosine similarity, özellikle metin ve vektör tabanlı verilerde yaygın olarak kullanılır.

Kosinüs benzerliği, iki vektör arasındaki açıya dayanarak benzerliği ölçen bir yöntemdir. Vektörler arasındaki açı ne kadar küçükse, yani vektörler birbirine ne kadar yakınsa, o kadar yüksek benzerlik vardır.


![Test](datasets/14.png)

<span style="color: blue; font-weight: bold;">COUNT VECTOR(Sayım Vektörü)</span>

Amacımız elimizdeki yorumları ölçülebilir bir forma getirmek.

![Test](datasets/15.png)

![Test](datasets/16.png)

<span style="color: blue; font-weight: bold;">TF-IDF</span>

Bir metin vektörleştirme yöntemidir. TF-IDF kelimelerin hem kendi metinlerinde hem de bütün odaklandığımız verideki geçme frekanları üzerinden bir normalizasyon işlemi yapar. Bir diğer ifadeyle oluşturacak olduğumuz kelime vektörlerini, dökümanterin  matrisini, bütün veriyi göz önünde bulundurarak ve terimlerinde frekansalrını göz önünde bulundurarak genel bir standartlaştırma işlemi yapar. Böylece count vektör yöntemi ile ortaya çıkabilecek bazı yanlılıkları giderir.

TF-IDF (Term Frequency-Inverse Document Frequency) bir kelimenin bir metin belgesinde veya bir dizi belgede ne kadar önemli olduğunu ölçen bir istatistiksel yöntemdir. Amacı, bir kelimenin hem sık kullanılmasını dikkate alıp hem de çok genel kelimelerin önemini azaltmaktır.

1.	TF (Term Frequency - Terim Frekansı):
o	Bir kelimenin belirli bir belgede kaç kez geçtiğini gösterir.


o	Genellikle, toplam kelime sayısına bölünerek normalize edilir.

o	Örnek:
"Python çok güçlü. Python öğrenmek istiyorum."
Burada "Python" kelimesi 2 kez geçtiği için TF değeri yüksektir.

3.	IDF (Inverse Document Frequency - Ters Belge Frekansı):
4.
o	Bir kelimenin, tüm belgeler arasında ne kadar yaygın veya nadir olduğunu gösterir.

o	Yaygın kelimelerin (örneğin, "ve", "bu", "çok") önemi düşürülürken, nadir kelimelerin önemi artırılır.

o	IDF değeri, kelimenin geçtiği belge sayısının toplam belge sayısına oranının logaritması ile hesaplanır:


![Test](datasets/17.png)

![Test](datasets/18.png)

![Test](datasets/19.png)

 <h1 style="text-align: center; color: RED">UYGULAMA</h1>

<span style="color: blue; font-weight: bold;">1-)İş Problemi</span>

Online film izleme platformu kullanıcılarına film önerilerinde bulunmak istemektedir.Kullanıcıların login oranı düşük olduğu için kullanıcı alışkanlıklarını toplayamamaktadır. Bu sebeple iş birlikçi filtreleme yöntemleri ile ürün önerileri geliştirememektedir.. Fakat kullanıcılaron tarayıcıdaki izlerinde hangi filmleri izlediklerini bilmektedir. Bu bilgilere göre film önerilerinde bulununuz.

<span style="color: blue; font-weight: bold;">2-)Veri Seti Hikayesi</span>

movies_metadata.csv veri seti 45000 film ile ilgili temel bilgileri barındırmkatadır. Uygulama kapsamında film açıklamalarını içeren 'overview' değişkeni ile çalışılacaktır.

<span style="color: blue; font-weight: bold;">3-)TF-IDF Matrisinin Oluşturulması</span>

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 500)
pd.set_option('display.expand_frame_repr', False)
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
df_ = pd.read_csv("C:\\Users\\ASLI\\Desktop\\Data Scientist Bootcamp\\5. Recommendation Systems\\datasets\\the_movies_dataset\\movies_metadata.csv",low_memory=False)

## low_memory=False DtypeWarning kapamak icin kullandık.

In [5]:
df = df_.copy()

In [7]:
df.head()

   adult                              belongs_to_collection    budget                                             genres                              homepage     id    imdb_id original_language               original_title                                           overview popularity                       poster_path                               production_companies                               production_countries release_date      revenue  runtime                                   spoken_languages    status                                            tagline                        title  video  vote_average  vote_count
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...  http://toystory.disney.com/toy-story    862  tt0114709                en                    Toy Story  Led by Woody, Andy's toys live happily in his ...  21.946943  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg     [{'name': 'Pixar Animation Studios', 'id': 3}]  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-10-30  373554033.0     81.0           [{'iso_639_1': 'en', 'name': 'English'}]  Released                                                NaN                    Toy Story  False           7.7      5415.0
1  False                                                NaN  65000000  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...                                   NaN   8844  tt0113497                en                      Jumanji  When siblings Judy and Peter discover an encha...  17.015539  /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg  [{'name': 'TriStar Pictures', 'id': 559}, {'na...  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-15  262797249.0    104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released          Roll the dice and unleash the excitement!                      Jumanji  False           6.9      2413.0
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...                                   NaN  15602  tt0113228                en             Grumpier Old Men  A family wedding reignites the ancient feud be...    11.7129  /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg  [{'name': 'Warner Bros.', 'id': 6194}, {'name'...  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-22          0.0    101.0           [{'iso_639_1': 'en', 'name': 'English'}]  Released  Still Yelling. Still Fighting. Still Ready for...             Grumpier Old Men  False           6.5        92.0
3  False                                                NaN  16000000  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...                                   NaN  31357  tt0114885                en            Waiting to Exhale  Cheated on, mistreated and stepped on, the wom...   3.859495  /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg  [{'name': 'Twentieth Century Fox Film Corporat...  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-22   81452156.0    127.0           [{'iso_639_1': 'en', 'name': 'English'}]  Released  Friends are the people who let you be yourself...            Waiting to Exhale  False           6.1        34.0
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0                     [{'id': 35, 'name': 'Comedy'}]                                   NaN  11862  tt0113041                en  Father of the Bride Part II  Just when George Banks has recovered from his ...   8.387519  /e64sOI48hQXyru7naBFyssKFxVd.jpg  [{'name': 'Sandollar Productions', 'id': 5842}...  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-02-10   76578911.0    106.0           [{'iso_639_1': 'en', 'name': 'English'}]  Released  Just When His World Is Back To Normal... He's ...  Father of the Bride Part II  False           5.7       173.0

In [9]:
df.shape

(45466, 24)

In [11]:
df['overview'].head() #burdaki açıklamaları matematiksel olarak ifade etme çabamız var.

0    Led by Woody, Andy's toys live happily in his ...
1    When siblings Judy and Peter discover an encha...
2    A family wedding reignites the ancient feud be...
3    Cheated on, mistreated and stepped on, the wom...
4    Just when George Banks has recovered from his ...
Name: overview, dtype: object

In [13]:
df[df['overview'].isnull()]#bu değişkendeki boş olan değerleri gösterir.

       adult belongs_to_collection    budget                                             genres         homepage      id    imdb_id original_language                    original_title overview popularity                       poster_path                               production_companies                               production_countries release_date     revenue  runtime                           spoken_languages    status tagline                             title  video  vote_average  vote_count
32     False                   NaN         0  [{'id': 10749, 'name': 'Romance'}, {'id': 12, ...              NaN   78802  tt0114952                fr  Guillaumet, les ailes du courage      NaN   0.745542  /k6ODtR38dKEfuzSGjggr8KDyAF4.jpg    [{'name': 'Iwerks Entertainment', 'id': 70801}]  [{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...   1996-09-18         0.0     50.0   [{'iso_639_1': 'en', 'name': 'English'}]  Released     NaN                  Wings of Courage  False           6.8         4.0
300    False                   NaN  22000000  [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...              NaN  161495  tt0114296                sv                         Roommates      NaN   3.395867  /hvHNlMvWS2GBt7RR971bJ3k4bJc.jpg  [{'name': 'Hollywood Pictures', 'id': 915}, {'...  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-03-01  12400000.0    108.0   [{'iso_639_1': 'en', 'name': 'English'}]  Released     NaN                         Roommates  False           6.4         7.0
634    False                   NaN         0                     [{'id': 35, 'name': 'Comedy'}]              NaN  287305  tt0117312                de    Peanuts – Die Bank zahlt alles      NaN   0.066123  /wpk30SvRHmjC2plgKHZXxG0FlKd.jpg  [{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...          [{'iso_3166_1': 'DE', 'name': 'Germany'}]   1996-03-21         0.0      NaN                                         []  Released     NaN    Peanuts – Die Bank zahlt alles  False           4.0         1.0
635    False                   NaN         0                     [{'id': 35, 'name': 'Comedy'}]              NaN  339428  tt0116485                de                     Happy Weekend      NaN   0.002229                               NaN   [{'name': 'Senator Film Produktion', 'id': 191}]          [{'iso_3166_1': 'DE', 'name': 'Germany'}]   1996-03-14     65335.0      NaN   [{'iso_639_1': 'de', 'name': 'Deutsch'}]  Released     NaN                     Happy Weekend  False           0.0         0.0
641    False                   NaN         0                     [{'id': 35, 'name': 'Comedy'}]              NaN   10801  tt0117788                de                     Das Superweib      NaN   0.821299  /AbhMKCh3fV5PY2B9uSPF1DWEvq2.jpg            [{'name': 'Constantin Film', 'id': 47}]          [{'iso_3166_1': 'DE', 'name': 'Germany'}]   1996-03-06         0.0     86.0   [{'iso_639_1': 'de', 'name': 'Deutsch'}]  Released     NaN                     The Superwife  False           5.3         7.0
...      ...                   ...       ...                                                ...              ...     ...        ...               ...                               ...      ...        ...                               ...                                                ...                                                ...          ...         ...      ...                                        ...       ...     ...                               ...    ...           ...         ...
45342  False                   NaN         0                      [{'id': 18, 'name': 'Drama'}]              NaN  199887  tt1771636                en                        Over/Under      NaN   0.704642  /1xLaIBGGPE4APtBJdfeuyOWICZ0.jpg  [{'name': 'Fox Television Studios', 'id': 6529...  [{'iso_3166_1': 'US', 'name': 'United States o...   2013-01-04         0.0     87.0   [{'iso_639_1': 'en', 'name': 'English'}]  Released     NaN                        Over/Under  False           4.0         2.0
45377  False                   NaN         0                  [{'id': 12, 'name': 'Adventure'}]              NaN  317389  tt0070695                es     Simbad e il califfo di Bagdad      NaN   0.006352  /izk7KbT6LZO9baEhCkOZYMgj60w.jpg  [{'name': 'Roas Produzioni', 'id': 21137}, {'n...            [{'iso_3166_1': 'IT', 'name': 'Italy'}]   1973-07-22         0.0      NaN  [{'iso_639_1': 'it', 'name': 'Italiano'}]  Released     NaN     Simbad e il califfo di Bagdad  False           0.0         0.0
45398  False                   NaN   1254040  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...  http://lmtr.fi/  468707  tt5742932                fi  Lauri Mäntyvaaran tuuheet ripset      NaN   0.347806  /rKOpJuwb7pTqYVShHM2tl25VxyF.jpg    [{'name': 'Elokuvayhtiö Oy Aamu', 'id': 84883}]          [{'iso_3166_1': 'FI', 'name': 'Finland'}]   2017-07-28         0.0     90.0     [{'iso_639_1': 'fi', 'name': 'suomi'}]  Released     NaN  Thick Lashes of Lauri Mäntyvaara  False           8.0         1.0
45399  False                   NaN    750000  [{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...              NaN  280422  tt3805180                ru                       Все и сразу      NaN   0.201582  /hNsmPpl3zLG36jr4EIEd5P8I4pa.jpg  [{'name': 'Кинокомпания «Lunapark»', 'id': 420...           [{'iso_3166_1': 'RU', 'name': 'Russia'}]   2014-06-05         3.0      0.0   [{'iso_639_1': 'ru', 'name': 'Pусский'}]  Released     NaN                       All at Once  False           6.0         4.0
45410  False                   NaN         0  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...              NaN  449131  tt0321264                ru                             Aprel      NaN   0.008903                               NaN                                                 []           [{'iso_3166_1': 'RU', 'name': 'Russia'}]          NaN         0.0      NaN                                         []  Released     NaN                             Aprel  False           6.0         1.0

[954 rows x 24 columns]

In [15]:
df['overview'] = df['overview'].fillna('')#eksik değerleri silemk yerine boşluk ile doldurmayı tercih ettik.

In [17]:
df['overview'].isnull().any()#boş değer kaldı mı diye kontrol ettik

False

In [19]:
tfidf = TfidfVectorizer(stop_words='english')

* Yukarıdaki kod parçası bir TF-IDF vektörleştirici (dönüştürücü) nesnesi oluşturur.Bu nesne, bir metin veri kümesini sayısal vektörlere dönüştürmek için kullanılır.stop_words='english' parametresi sayesinde, İngilizce'deki gereksiz kelimeleri (stop words) (örneğin: "the", "is", "in", "and", vb.) filtreler.Çünkü bu kelimeler modele fazla bilgi vermez ama çok yer kaplar. Eğer stop_words bu parametreyi kullanmasaydık tüm kelimeleri alırdı. Bu da modeli gereksiz gürültüyle doldurabilir.

TF = Term Frequency = Terim Frekansı=Bir kelimenin, bir belgede kaç kez geçtiğini gösterir.

In [22]:
tfidf_matrix = tfidf.fit_transform(df['overview'])

TfidfVectorizer iki temel işlevi birleştirir:

fit() → Tüm kelimeleri tarar, hangi kelimelerin olduğunu öğrenir (sözlük = vocabulary oluşturur).

transform() → Metinleri bu sözlüğe göre sayısallaştırır.

tfidf_matrix = Her satırı bir filme, her sütunu bir kelimeye karşılık gelen sparse matrix (seyrek matris)

In [25]:
tfidf_matrix.shape #satırlarda filmler sutunlarda eşsiz kelimeler bulunmaktadır.
#Satır ve sutunların kesişiminde tf-ıdf skorları bulunmaktadır.

(45466, 75827)

In [27]:
tfidf.get_feature_names_out()#eşsiz kelimeleri gösterir.

array(['00', '000', '000km', ..., '첫사랑', 'ﬁrst', 'ﬁve'], dtype=object)

In [29]:
list(tfidf.get_feature_names_out())

['00',
 '000',
 '000km',
 '000th',
 '001',
 '006',
 '007',
 '008',
 '009',
 '0093',
 '01',
 '0123',
 '02',
 '03',
 '04',
 '042',
 '05',
 '05pm',
 '06',
 '07',
 '077',
 '07am',
 '08',
 '088',
 '09',
 '10',
 '100',
 '1000',
 '10000',
 '1000s',
 '1000th',
 '1001',
 '100th',
 '101',
 '101st',
 '103',
 '103rd',
 '104',
 '105',
 '1066',
 '108',
 '1080s',
 '108th',
 '109',
 '10b',
 '10crores',
 '10mn',
 '10th',
 '10x',
 '11',
 '110',
 '1100',
 '111',
 '112',
 '1138',
 '114',
 '115',
 '117',
 '117a',
 '118',
 '1183',
 '119',
 '11s',
 '11th',
 '12',
 '120',
 '1200',
 '1200s',
 '1206',
 '1215',
 '1218',
 '1227',
 '125',
 '1250',
 '125th',
 '1263',
 '129',
 '12th',
 '13',
 '130',
 '1300',
 '1300s',
 '1302',
 '1303',
 '133',
 '134',
 '1344',
 '1348',
 '1349',
 '138',
 '13anos',
 '13b',
 '13s',
 '13th',
 '14',
 '140',
 '1400',
 '1408',
 '1413',
 '142',
 '1429',
 '143',
 '144',
 '145',
 '1458',
 '146',
 '1463',
 '1466',
 '1472',
 '1475',
 '148',
 '1482',
 '1483',
 '1492',
 '14pm',
 '14th',
 '15',
 '150',
 '1500',
 '150000',
 '1500s',
 '1509',
 '150th',
 '1518',
 '1520s',
 '1526',
 '1528',
 '1536',
 '1537',
 '1543',
 '1547',
 '1548',
 '155',
 '1557',
 '1560',
 '1561',
 '1562',
 '1564',
 '1570',
 '1572',
 '1575',
 '1582',
 '1587',
 '1588',
 '1590',
 '1592',
 '1593',
 '1594',
 '1595',
 '1597',
 '1598',
 '1599',
 '15th',
 '15yrs',
 '15½',
 '16',
 '160',
 '1600',
 '1600s',
 '1600th',
 '1601',
 '1606',
 '161',
 '1610',
 '1612',
 '1614',
 '1615',
 '1616',
 '1625',
 '1626',
 '1630s',
 '1637',
 '1639',
 '164',
 '1640s',
 '1642',
 '1644',
 '1648',
 '1649',
 '165',
 '1651',
 '1653',
 '1654',
 '1656',
 '1666',
 '1669',
 '1671',
 '1678',
 '168',
 '1681',
 '1683',
 '1684',
 '1689',
 '168th',
 '1691',
 '1692',
 '1695',
 '1699',
 '16mm',
 '16th',
 '16yo',
 '17',
 '170',
 '1700',
 '1700s',
 '1701',
 '1710',
 '1715',
 '1716',
 '1724',
 '174',
 '1740',
 '1745',
 '1746',
 '1748',
 '175',
 '1757',
 '1760',
 '1760s',
 '1776',
 '1777',
 '1783',
 '1786',
 '1787',
 '1789',
 '1790s',
 '1791',
 '1792',
 '1793',
 '1794',
 '1797',
 '17months',
 '17th',
 '18',
 '180',
 '1800',
 '1800s',
 '1804',
 '1805',
 '1808',
 '1809',
 '180km',
 '180sm',
 '181',
 '1810',
 '1810s',
 '1811',
 '1812',
 '1813',
 '1814',
 '1815',
 '1816',
 '1817',
 '1818',
 '1819',
 '182',
 '1820',
 '1820s',
 '1823',
 '1824',
 '1825',
 '1826',
 '1828',
 '1830',
 '1830s',
 '1831',
 '1835',
 '1836',
 '1838',
 '1839',
 '184',
 '1840',
 '1840s',
 '1841',
 '1842',
 '1843',
 '1845',
 '1846',
 '1847',
 '1848',
 '1849',
 '185',
 '1850',
 '1850s',
 '1851',
 '1852',
 '1853',
 '1854',
 '1856',
 '1857',
 '1858',
 '1859',
 '186',
 '1860',
 '1860s',
 '1861',
 '1862',
 '1863',
 '1864',
 '1865',
 '1866',
 '1867',
 '1868',
 '1869',
 '1870',
 '1870s',
 '1871',
 '1873',
 '1874',
 '1875',
 '1876',
 '1877',
 '1878',
 '1879',
 '1880',
 '1880s',
 '1881',
 '1882',
 '1883',
 '1884',
 '1885',
 '1886',
 '1887',
 '1888',
 '1889',
 '1890',
 '1890s',
 '1891',
 '1892',
 '1893',
 '1894',
 '1895',
 '1896',
 '1897',
 '1898',
 '1899',
 '18th',
 '19',
 '190',
 '1900',
 '1900s',
 '1901',
 '1902',
 '1903',
 '1904',
 '1905',
 '1906',
 '1907',
 '1908',
 '1909',
 '191',
 '1910',
 '1910s',
 '1911',
 '1912',
 '1913',
 '1914',
 '1915',
 '1916',
 '1917',
 '1918',
 '1919',
 '192',
 '1920',
 '1920s',
 '1921',
 '1922',
 '1923',
 '1924',
 '1925',
 '1926',
 '1927',
 '1928',
 '1929',
 '1930',
 '1930s',
 '1931',
 '1932',
 '1933',
 '1934',
 '1935',
 '1936',
 '1937',
 '1938',
 '1939',
 '1940',
 '1940s',
 '1941',
 '1942',
 '1943',
 '1944',
 '1945',
 '1946',
 '1947',
 '1948',
 '1949',
 '1950',
 '1950s',
 '1951',
 '1952',
 '1953',
 '1954',
 '1955',
 '1956',
 '1957',
 '1958',
 '1959',
 '1960',
 '1960s',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1980s',
 '1980th',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1990s',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '19th',
 '19yo',
 '1felco',
 '1st',
 '20',
 '200',
 '2000',
 '20000',
 '2000ad',
 '2000s',
 '2000th',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2010fred',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2024',
 '2025',
 '2027',
 '2028',
 '2029',
 '2030',
 '2031',
 '2032',
 '2033',
 '2034',
 '2035',
 '2036',
 '2037',
 '2038',
 '2039',
 '2040',
 '2041',
 '2043',
 '2045',
 '2046',
 '2047',
 '2049',
 '2050',
 '2052',
 '2054',
 '2055',
 '2057',
 '2058',
 '2067',
 '2071',
 '2073',
 '2074',
 '2077',
 '2078',
 '208',
 '2081',
 '2084',
 '2087',
 '2092',
 '2095',
 '2096',
 '20s',
 '20something',
 '20th',
 '20xx',
 '21',
 '2100',
 '211',
 '2116',
 '212th',
 '213',
 '2150',
 '2159',
 '2163',
 '2167',
 '2199',
 '21rst',
 '21st',
 '22',
 '220',
 '2204',
 '221b',
 '223',
 '224',
 '2247',
 '2257',
 '226',
 '2267',
 '227',
 '229',
 '22nd',
 '23',
 '230',
 '2300',
 '2306',
 '2314',
 '234',
 '235',
 '236',
 '23rd',
 '24',
 '240',
 '2400',
 '242',
 '2455',
 '247',
 '2470',
 '248',
 '2491',
 '24h',
 '24th',
 '24yo',
 '25',
 '250',
 '2500',
 '25000',
 '2505',
 '2509',
 '250cc',
 '250th',
 '25143',
 '252',
 '2525',
 '257',
 '2577',
 '25k',
 '25th',
 '26',
 '260',
 '2600',
 '26000',
 '26th',
 '27',
 '2700',
 '2707',
 '2710',
 '276',
 '2784',
 '27th',
 '28',
 '280',
 '2808a',
 '280z',
 '286',
 '28th',
 '29',
 '2961',
 '29th',
 '2channel',
 '2d',
 '2ldk',
 '2m',
 '2manydj',
 '2nd',
 '2pac',
 '30',
 '300',
 '3000',
 '30000',
 '300000',
 '301',
 '302',
 '303',
 '305',
 '308th',
 '309',
 '30s',
 '30th',
 '31',
 '310lb',
 '3127',
 '316th',
 '318',
 '31st',
 '32',
 '320',
 '327',
 '33',
 '330',
 '3313',
 '332',
 '34',
 '341',
 '344m',
 '345',
 '346',
 '35',
 '350',
 '350lbs',
 '356',
 '359',
 '35mm',
 '35th',
 '36',
 '360',
 '365',
 '36th',
 '37',
 '370',
 '371',
 '375',
 '37th',
 '38',
 '383',
 '38th',
 '39',
 '396',
 '39th',
 '3a',
 '3am',
 '3d',
 '3dd',
 '3km',
 '3pm',
 '3po',
 '3rd',
 '3v3',
 '3½',
 '40',
 '400',
 '4000',
 '40000',
 '405',
 '407',
 '40s',
 '40ste',
 '40th',
 '41',
 '410',
 '413lbs',
 '41c',
 '41st',
 '42',
 '420',
 '422',
 '422nd',
 '427',
 '429',
 '43',
 '430',
 '436',
 '43rd',
 '44',
 '440',
 '442nd',
 '444th',
 '45',
 '450',
 '45365',
 '45s',
 '45th',
 '46',
 '465',
 '47',
 '47s',
 '47th',
 '48',
 '480',
 '485',
 '48hr',
 '48th',
 '49',
 '497',
 '49th',
 '4am',
 '4bia',
 '4chan',
 '4eb',
 '4ever',
 '4f',
 '4k',
 '4kids',
 '4million',
 '4th',
 '50',
 '500',
 '5000',
 '500th',
 '501',
 '501st',
 '506',
 '509th',
 '50enne',
 '50s',
 '50th',
 '51',
 '515',
 '5150',
 '51st',
 '52',
 '5200',
 '522',
 '52min',
 '52nd',
 '53',
 '530',
 '5307th',
 '533',
 '536',
 '54',
 '54th',
 '55',
 '56',
 '56pm',
 '56th',
 '57',
 '57th',
 '58',
 '59',
 '5am',
 '5m',
 '5th',
 '60',
 '600',
 '6000',
 '605',
 '60s',
 '60th',
 '61',
 '612',
 '617',
 '62',
 '625',
 '63',
 '633',
 '638',
 '64',
 '643',
 '65',
 '658',
 '65k',
 '65th',
 '66',
 '663',
 '666',
 '66th',
 '67',
 '670',
 '68',
 '68th',
 '69',
 '6am',
 '6b',
 '6m',
 '6th',
 '6wing',
 '70',
 '700',
 '701',
 '707',
 '70mm',
 '70s',
 '70th',
 '71',
 '71099',
 '7117',
 '72',
 '725',
 '73',
 '731',
 '74',
 '740',
 '743',
 '747',
 '74th',
 '75',
 '750',
 '7500',
 '751',
 '757',
 '75th',
 '76',
 '76ers',
 '76th',
 '77',
 '77th',
 '78',
 '79',
 '7days',
 '7pm',
 '7th',
 '80',
 '800',
 '8000',
 '800m',
 '808',
 '80s',
 '80th',
 '81',
 '82',
 '825',
 '83',
 '83rd',
 '84',
 '85',
 '850',
 '85million',
 '85th',
 '86',
 '87',
 '88',
 '880',
 '88888',
 '89',
 '8km',
 '8m',
 '8mm',
 '8pm',
 '8th',
 '8x10',
 '8½',
 '90',
 '900',
 '9000',
 '900lb',
 '90210',
 '907',
 '90s',
 '90th',
 '91',
 '911',
 '91st',
 '92',
 '922',
 '929',
 '92nd',
 '93',
 '937',
 '94',
 '9413',
 '95',
 '95er',
 '96',
 '964',
 '97',
 '976',
 '977',
 '98',
 '99',
 '999',
 '9mm',
 '9pm',
 '9th',
 '9to5',
 '_stakeout_',
 '_wizard',
 'a2',
 'a300',
 'aa',
 'aaa',
 'aaaron',
 'aab',
 'aachan',
 'aachi',
 'aackerlund',
 'aadhavan',
 'aadhi',
 'aadland',
 'aaicha',
 'aakash',
 'aake',
 'aalavandhan',
 'aalst',
 'aaltonen',
 'aames',
 'aamir',
 'aan',
 'aanandam',
 'aang',
 'aangehouden',
 'aanmodderfakker',
 'aapeli',
 'aarakshan',
 'aarchi',
 'aarne',
 'aarno',
 'aaron',
 'aarons',
 'aarp',
 'aart',
 'aarti',
 'aarya',
 'aarón',
 'aasen',
 'aashirvad',
 'aashish',
 'aasia',
 'aati',
 'aatish',
 'ab',
 'aba',
 'ababa',
 'abacco',
 'aback',
 'abacus',
 'abaddon',
 'abagnale',
 'abahachi',
 'abalaba',
 'aballay',
 'abalone',
 'abandon',
 'abandond',
 'abandoned',
 'abandoning',
 'abandonment',
 'abandons',
 'abar',
 'abard',
 'abargil',
 'abas',
 'abatcha',
 'abates',
 'abati',
 'abba',
 'abbaji',
 'abbas',
 'abbaseya',
 'abbasi',
 'abbass',
 'abbe',
 'abberline',
 'abbes',
 'abbess',
 'abbey',
 'abbia',
 'abbie',
 'abbot',
 'abbott',
 'abby',
 'abbé',
 'abc',
 'abcs',
 'abdallah',
 ...]

<span style="color: blue; font-weight: bold;">4-)COSİNE SİMİLARİTY MATRİSİNİN OLUŞTURULMASI</span>

In [ ]:
cosine_sim = cosine_similarity(tfidf_matrix,tfidf_matrix)#bu matriste her bir filmin diğer film ile benzerlik skoru bulunmaktadır.

In [ ]:
cosine_sim.shape

<span style="color: blue; font-weight: bold;">5-)BENZERLİKLERE GÖRE ÖNERİLERİN YAPILMASI</span>

In [ ]:
indices = pd.Series(df.index, index=df['title'])#Film adlarıyla onların satır indeksini eşleştirir

In [ ]:
indices.index.value_counts()#çıktıya bakıldığında indexlerde yani filmlerde çoklama olduğu görülüyor.

In [ ]:
indices = indices[~indices.index.dulicated(keep='last')]

TfidfVectorizer ve öneri sistemleriyle çalışırken:

Film adları (df['title']) benzersiz (unique) olmalıdır.

Eğer aynı film adı birden fazla satırda varsa, .loc['Film Adı'] gibi erişimler hatalı çalışabilir veya birden fazla eşleşme döndürür.

Bu kodla tekrarlayan film adlarını temizliyoruz, sadece sonuncusunu tutuyoruz.

indices.index.duplicated(keep='last')
Bu satır:

indices'in index'inde (yani film adlarında) hangi değerlerin tekrar ettiğini bulur.

keep='last': Eğer aynı film adı birden fazla varsa, sadece en sonuncusunu tut; diğerlerini "tekrar" olarak işaretle.

~ (Tilde)
Bu, boolean serisini tersine çevirir (NOT işlemi gibi düşünebilirsin).

In [ ]:
movie_index = indicec['Sherlock Holmes']

In [ ]:
cosine_sim[movie_index]#sherlock holmes ile diğer filmlerin benzerlik skorlarını getirir.

In [ ]:
sim_score = pd.DataFrame(cosine_sim[movie_index], columns['score'])#okunabilirk açısından yaptık

In [ ]:
movie_indices = sim_score.sort_values('score', ascending=False)[1:11].index
#sic_score dataframeini yüksek skordan başlayarak sıraladık. 1. index ile 10. indexi şectik 0. index filmin kendisi old. için almadık
#.index ile o filmlerin index bilgilerine eriştik.Yani en cok benzerliği olan 10 filmin indexi elimizde

In [ ]:
df['title'].iloc[movie_indices]#film indexlerini kullanarak film isimlerine eriştik.

<span style="color: blue; font-weight: bold;">5-)ÇALIŞMANIN SCRİPTİNİN HAZIRLANMASI</span>

In [ ]:
def calculate_cosine_sim(dataframe):
    tfidf = TfidfVectorizer(stop_words='english')
    dataframe['overview'] = dataframe['overview'].fillna('')
    tfidf_matrix = tfidf.fit_transform(dataframe['overview'])
    cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
    return cosine_sim

def content_based_recommender(title, cosine_sim, dataframe):
    # index'leri olusturma
    indices = pd.Series(dataframe.index, index=dataframe['title'])
    indices = indices[~indices.index.duplicated(keep='last')]
    # title'ın index'ini yakalama
    movie_index = indices[title]
    # title'a gore benzerlik skorlarını hesapalama
    similarity_scores = pd.DataFrame(cosine_sim[movie_index], columns=["score"])
    # kendisi haric ilk 10 filmi getirme
    movie_indices = similarity_scores.sort_values("score", ascending=False)[1:11].index
    return dataframe['title'].iloc[movie_indices]

content_based_recommender("Sherlock Holmes", cosine_sim, df)

content_based_recommender("The Matrix", cosine_sim, df)

content_based_recommender("The Godfather", cosine_sim, df)

content_based_recommender('The Dark Knight Rises', cosine_sim, df)


cosine_sim = calculate_cosine_sim(df)
content_based_recommender('The Dark Knight Rises', cosine_sim, df)